In [1]:
import numpy as np
import scipy.fftpack as fp

import scipy.linalg  as lg

np.set_printoptions(precision=3, suppress=True)
π= np.pi
π

3.141592653589793

In [3]:
x= np.array([1,0,0,0,0,0,0,0])
X= fp.fft(x)
X

array([1.-0.j, 1.+0.j, 1.-0.j, 1.+0.j, 1.-0.j, 1.-0.j, 1.+0.j, 1.-0.j])

In [13]:
x= np.array([1,1,1,1,1,1,1,1])
X= fp.fft(x)
X

array([8.-0.j, 0.+0.j, 0.-0.j, 0.+0.j, 0.-0.j, 0.-0.j, 0.+0.j, 0.-0.j])

In [14]:
x= np.array([1,-1,1,-1,1,-1,1,-1])
X= fp.fft(x)
X

array([0.-0.j, 0.+0.j, 0.-0.j, 0.+0.j, 8.-0.j, 0.-0.j, 0.+0.j, 0.-0.j])

In [22]:
x= np.array([3,0,2,0,2,0,2,0])
X= fp.fft(x)
X

array([9.-0.j, 1.+0.j, 1.-0.j, 1.+0.j, 9.-0.j, 1.-0.j, 1.+0.j, 1.-0.j])

In [25]:
x= np.array([1,1,0,0,0,0,1,1])
X= fp.ifft(x)
X

array([ 0.5  -0.j   ,  0.302-0.125j,  0.   +0.j   , -0.052+0.125j,
        0.   -0.j   , -0.052-0.125j,  0.   -0.j   ,  0.302+0.125j])

In [30]:
y= np.array([1,1,0,0,0,0,0,1])
Y= fp.ifft(y)
Y

array([ 0.375-0.j,  0.302-0.j,  0.125+0.j, -0.052-0.j, -0.125-0.j,
       -0.052+0.j,  0.125-0.j,  0.302+0.j])

In [27]:
x= np.array([1,1,0,0])
X= fp.fft(x)
X

array([2.-0.j, 1.-1.j, 0.-0.j, 1.+1.j])

In [33]:
y= np.array([1,1,0,0,0,0,0,0])
Y= fp.fft(y)
Y

array([2.   -0.j   , 1.707-0.707j, 1.   -1.j   , 0.293-0.707j,
       0.   -0.j   , 0.293+0.707j, 1.   +1.j   , 1.707+0.707j])

In [35]:
x= np.array([1,1,1,1])
X= fp.fft(x)
X

array([4.-0.j, 0.+0.j, 0.-0.j, 0.-0.j])